import { ROLES, type Role } from './roles';

export const PERMISSIONS = {
  // Student & Parent permissions
  VIEW_OWN_PROGRESS: [ROLES.STUDENT, ROLES.PARENT],

  // Data access permissions
  VIEW_STUDENT_DATA: [ROLES.EDUCATOR, ROLES.SCHOOL_ADMIN, ROLES.DISTRICT_ADMIN, ROLES.PLATFORM_ADMIN],
  VIEW_CURRICULUM: [ROLES.EDUCATOR, ROLES.SCHOOL_ADMIN, ROLES.DISTRICT_ADMIN, ROLES.PLATFORM_ADMIN, ROLES.STUDENT],

  // Class management permissions
  MANAGE_CLASSES: [ROLES.EDUCATOR, ROLES.SCHOOL_ADMIN, ROLES.DISTRICT_ADMIN],
  MANAGE_IEP: [ROLES.EDUCATOR, ROLES.SCHOOL_ADMIN],

  // Curriculum management permissions (granular)
  MANAGE_GLOBAL_CURRICULUM: [ROLES.PLATFORM_ADMIN], // Only SuperAdmins can modify global curriculum
  MANAGE_SCHOOL_CURRICULUM: [ROLES.SCHOOL_ADMIN, ROLES.DISTRICT_ADMIN, ROLES.PLATFORM_ADMIN], // School-level customization
  MANAGE_CLASSROOM_LEARNING_PATHS: [ROLES.EDUCATOR, ROLES.SCHOOL_ADMIN, ROLES.DISTRICT_ADMIN, ROLES.PLATFORM_ADMIN], // Teachers can customize their classroom paths

  // Compliance & administrative permissions
  VIEW_COMPLIANCE: [ROLES.EDUCATOR, ROLES.SCHOOL_ADMIN, ROLES.DISTRICT_ADMIN, ROLES.PLATFORM_ADMIN],
  MANAGE_BILLING: [ROLES.SCHOOL_ADMIN, ROLES.DISTRICT_ADMIN, ROLES.PLATFORM_ADMIN],
  MANAGE_TENANT: [ROLES.DISTRICT_ADMIN, ROLES.PLATFORM_ADMIN],
  PLATFORM_ADMIN: [ROLES.PLATFORM_ADMIN],
} as const;

export function hasPermission(userRole: Role, permission: keyof typeof PERMISSIONS): boolean {
  return (PERMISSIONS[permission] as readonly string[]).includes(userRole);
}
