import { ROLES, type Role } from './roles';

export const PERMISSIONS = {
  VIEW_OWN_PROGRESS: [ROLES.STUDENT, ROLES.PARENT],
  VIEW_STUDENT_DATA: [ROLES.EDUCATOR, ROLES.SCHOOL_ADMIN, ROLES.DISTRICT_ADMIN, ROLES.PLATFORM_ADMIN],
  MANAGE_CLASSES: [ROLES.EDUCATOR, ROLES.SCHOOL_ADMIN, ROLES.DISTRICT_ADMIN],
  MANAGE_IEP: [ROLES.EDUCATOR, ROLES.SCHOOL_ADMIN],
  VIEW_COMPLIANCE: [ROLES.EDUCATOR, ROLES.SCHOOL_ADMIN, ROLES.DISTRICT_ADMIN, ROLES.PLATFORM_ADMIN],
  MANAGE_BILLING: [ROLES.SCHOOL_ADMIN, ROLES.DISTRICT_ADMIN, ROLES.PLATFORM_ADMIN],
  MANAGE_TENANT: [ROLES.DISTRICT_ADMIN, ROLES.PLATFORM_ADMIN],
  PLATFORM_ADMIN: [ROLES.PLATFORM_ADMIN],
} as const;

export function hasPermission(userRole: Role, permission: keyof typeof PERMISSIONS): boolean {
  return (PERMISSIONS[permission] as readonly string[]).includes(userRole);
}
