'use client';

import { useEffect, useState } from 'react';

type TenantRow = {
  id: string;
  name: string;
  slug: string;
  subscriptionTier: string;
  subscriptionStatus: string;
  isSuspended: boolean;
  suspendedAt: string | null;
  suspensionReason: string | null;
  users: number;
  schools: number;
  sessionCountThisMonth: number;
  tokenCountThisMonth: number;
  aiCostUsdThisMonth: number;
};

type DashboardData = {
  summary: {
    tenantCount: number;
    suspendedTenantCount: number;
    sessionsThisMonth: number;
    aiTokensThisMonth: number;
    aiCostUsdThisMonth: number;
  };
  tenantRows: TenantRow[];
  recentAuditEvents: Array<{
    id: string;
    tenantId: string;
    action: string;
    resource: string;
    timestamp: string;
  }>;
};

export function SuperAdminDashboard() {
  const [data, setData] = useState<DashboardData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchData = async () => {
    try {
      const response = await fetch('/api/admin/super/overview');
      if (!response.ok) {
        const body = await response.json();
        throw new Error(body.error ?? 'Failed to fetch super admin data.');
      }

      setData(await response.json());
      setError(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const toggleSuspension = async (tenant: TenantRow) => {
    const reason = tenant.isSuspended ? undefined : window.prompt('Reason for suspension:') ?? undefined;
    if (!tenant.isSuspended && !reason) {
      return;
    }

    const response = await fetch(`/api/admin/super/tenants/${tenant.id}/suspension`, {
      method: 'PATCH',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ suspend: !tenant.isSuspended, reason }),
    });

    if (!response.ok) {
      const body = await response.json();
      alert(body.error ?? 'Failed to update tenant suspension state.');
      return;
    }

    await fetchData();
  };

  const addIntervention = async (tenant: TenantRow) => {
    const summary = window.prompt(`Intervention summary for ${tenant.name}:`);
    if (!summary) return;

    const details = window.prompt('Optional detailed notes (can be left blank):') ?? undefined;
    const response = await fetch(`/api/admin/super/tenants/${tenant.id}/interventions`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ summary, details }),
    });

    if (!response.ok) {
      const body = await response.json();
      alert(body.error ?? 'Failed to log intervention.');
      return;
    }

    alert('Intervention logged.');
    await fetchData();
  };

  const createInvoice = async (tenant: TenantRow) => {
    const description = window.prompt(`Invoice line item description for ${tenant.name}:`, 'District monthly subscription');
    if (!description) return;

    const amountInput = window.prompt('Amount in USD (example: 2999):', '2999');
    if (!amountInput) return;
    const amountUsd = Number(amountInput);
    if (Number.isNaN(amountUsd) || amountUsd <= 0) {
      alert('Invalid amount.');
      return;
    }

    const response = await fetch(`/api/admin/super/tenants/${tenant.id}/invoice`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        memo: 'Manual district invoice generated by super admin dashboard',
        lineItems: [{ description, unitAmountCents: Math.round(amountUsd * 100), quantity: 1 }],
      }),
    });

    const body = await response.json();
    if (!response.ok) {
      alert(body.error ?? 'Failed to create invoice.');
      return;
    }

    alert(`Invoice created: ${body.invoiceId}`);
  };

  if (loading) return <div className="p-6">Loading super admin dashboard…</div>;
  if (error) return <div className="p-6 text-red-600">{error}</div>;
  if (!data) return null;

  return (
    <div className="container mx-auto max-w-7xl space-y-6 px-4 py-8">
      <div>
        <h1 className="text-3xl font-bold">Super Admin “God Mode” Dashboard</h1>
        <p className="text-gray-600">Tenant controls, district billing, cross-tenant analytics, and intervention tooling.</p>
      </div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-5">
        <StatCard label="Tenants" value={String(data.summary.tenantCount)} />
        <StatCard label="Suspended" value={String(data.summary.suspendedTenantCount)} />
        <StatCard label="Sessions (month)" value={String(data.summary.sessionsThisMonth)} />
        <StatCard label="AI Tokens (month)" value={data.summary.aiTokensThisMonth.toLocaleString()} />
        <StatCard label="AI Cost (month)" value={`$${data.summary.aiCostUsdThisMonth.toFixed(2)}`} />
      </div>

      <div className="rounded-lg border bg-white shadow">
        <table className="w-full text-sm">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-3 py-2 text-left">Tenant</th>
              <th className="px-3 py-2 text-left">Subscription</th>
              <th className="px-3 py-2 text-left">Usage</th>
              <th className="px-3 py-2 text-left">Status</th>
              <th className="px-3 py-2 text-left">Actions</th>
            </tr>
          </thead>
          <tbody>
            {data.tenantRows.map((tenant) => (
              <tr key={tenant.id} className="border-t align-top">
                <td className="px-3 py-2">
                  <p className="font-medium">{tenant.name}</p>
                  <p className="text-xs text-gray-600">{tenant.slug}</p>
                </td>
                <td className="px-3 py-2">
                  <p>{tenant.subscriptionTier}</p>
                  <p className="text-xs text-gray-600">{tenant.subscriptionStatus}</p>
                </td>
                <td className="px-3 py-2 text-xs">
                  <p>Users: {tenant.users}</p>
                  <p>Schools: {tenant.schools}</p>
                  <p>Sessions: {tenant.sessionCountThisMonth}</p>
                  <p>Tokens: {tenant.tokenCountThisMonth.toLocaleString()}</p>
                </td>
                <td className="px-3 py-2">
                  <span className={tenant.isSuspended ? 'text-red-700' : 'text-green-700'}>
                    {tenant.isSuspended ? 'Suspended' : 'Active'}
                  </span>
                  {tenant.suspensionReason ? <p className="text-xs text-gray-600">{tenant.suspensionReason}</p> : null}
                </td>
                <td className="space-x-2 px-3 py-2">
                  <button className="rounded border px-2 py-1" onClick={() => toggleSuspension(tenant)}>
                    {tenant.isSuspended ? 'Restore' : 'Suspend'}
                  </button>
                  <button className="rounded border px-2 py-1" onClick={() => addIntervention(tenant)}>
                    Log Intervention
                  </button>
                  <button className="rounded border px-2 py-1" onClick={() => createInvoice(tenant)}>
                    Create Invoice
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="rounded-lg border bg-white p-4 shadow">
        <h2 className="mb-2 text-lg font-semibold">Recent global audit events</h2>
        <ul className="space-y-1 text-sm">
          {data.recentAuditEvents.map((event) => (
            <li key={event.id}>
              <span className="font-medium">{new Date(event.timestamp).toLocaleString()}:</span> {event.action} on {event.resource}{' '}
              <span className="text-gray-500">({event.tenantId})</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

function StatCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border bg-white p-4 shadow">
      <p className="text-sm text-gray-600">{label}</p>
      <p className="text-2xl font-semibold">{value}</p>
    </div>
  );
}
